# 20 samples
python main.py -c experiment_params/xlmr.ini --experiment_name zn_xlmr_20 --path_to_train_set data/MLDoc/mldoc_chinese_train.tsv path_to_test_set data/MLDoc/mldoc_chinese_test.tsv --tokenizer_type chinese --language chinese --percentage_dev 0.98
python main.py -c experiment_params/xlmr.ini --experiment_name ja_xlmr_20 --path_to_train_set data/MLDoc/mldoc_japanese_train.tsv --path_to_test_set  data/MLDoc/mldoc_japanese_test.tsv --tokenizer_type japanese --language japanese --percentage_dev 0.98
python main.py -c experiment_params/xlmr.ini --experiment_name de_xlmr_20 --path_to_train_set data/MLDoc/mldoc_german_train.tsv --path_to_test_set  data/MLDoc/mldoc_german_test.tsv --tokenizer_type whitespace --language german --percentage_dev 0.98
python main.py -c experiment_params/xlmr.ini --experiment_name es_xlmr_20 --path_to_train_set data/MLDoc/mldoc_spanish_train.tsv --path_to_test_set  data/MLDoc/mldoc_spanish_test.tsv --tokenizer_type whitespace --language spanish --percentage_dev 0.98
python main.py -c experiment_params/xlmr.ini --experiment_name en_xlmr_20 --path_to_train_set data/MLDoc/mldoc_english_train.tsv --path_to_test_set  data/MLDoc/mldoc_english_test.tsv --tokenizer_type whitespace --language english --percentage_dev 0.98
python main.py -c experiment_params/xlmr.ini --experiment_name fr_xlmr_20 --path_to_train_set data/MLDoc/mldoc_french_train.tsv --path_to_test_set  data/MLDoc/mldoc_french_test.tsv --tokenizer_type whitespace --language french --percentage_dev 0.98
python main.py -c experiment_params/xlmr.ini --experiment_name it_xlmr_20 --path_to_train_set data/MLDoc/mldoc_italian_train.tsv --path_to_test_set  data/MLDoc/mldoc_italian_test.tsv --tokenizer_type whitespace --language italian --percentage_dev 0.98
python main.py -c experiment_params/xlmr.ini --experiment_name ru_xlmr_20 --path_to_train_set data/MLDoc/mldoc_russian_train.tsv --path_to_test_set  data/MLDoc/mldoc_russian_test.tsv --tokenizer_type whitespace --language russian --percentage_dev 0.98

# 50 samples
python main.py -c experiment_params/xlmr.ini --experiment_name zn_xlmr_50 --path_to_train_set data/MLDoc/mldoc_chinese_train.tsv --path_to_test_set data/MLDoc/mldoc_chinese_test.tsv --tokenizer_type chinese --language chinese --percentage_dev 0.95
python main.py -c experiment_params/xlmr.ini --experiment_name ja_xlmr_50 --path_to_train_set data/MLDoc/mldoc_japanese_train.tsv --path_to_test_set  data/MLDoc/mldoc_japanese_test.tsv --tokenizer_type japanese --language japanese --percentage_dev 0.95
python main.py -c experiment_params/xlmr.ini --experiment_name de_xlmr_50 --path_to_train_set data/MLDoc/mldoc_german_train.tsv --path_to_test_set  data/MLDoc/mldoc_german_test.tsv --tokenizer_type whitespace --language german --percentage_dev 0.95
python main.py -c experiment_params/xlmr.ini --experiment_name en_xlmr_50 --path_to_train_set data/MLDoc/mldoc_english_train.tsv --path_to_test_set  data/MLDoc/mldoc_english_test.tsv --tokenizer_type whitespace --language english --percentage_dev 0.95
python main.py -c experiment_params/xlmr.ini --experiment_name es_xlmr_50 --path_to_train_set data/MLDoc/mldoc_spanish_train.tsv --path_to_test_set  data/MLDoc/mldoc_spanish_test.tsv --tokenizer_type whitespace --language spanish --percentage_dev 0.95
python main.py -c experiment_params/xlmr.ini --experiment_name fr_xlmr_50 --path_to_train_set data/MLDoc/mldoc_french_train.tsv --path_to_test_set  data/MLDoc/mldoc_french_test.tsv --tokenizer_type whitespace --language french --percentage_dev 0.95
python main.py -c experiment_params/xlmr.ini --experiment_name it_xlmr_50 --path_to_train_set data/MLDoc/mldoc_italian_train.tsv --path_to_test_set  data/MLDoc/mldoc_italian_test.tsv --tokenizer_type whitespace --language italian --percentage_dev 0.95
python main.py -c experiment_params/xlmr.ini --experiment_name ru_xlmr_50 --path_to_train_set data/MLDoc/mldoc_russian_train.tsv --path_to_test_set  data/MLDoc/mldoc_russian_test.tsv --tokenizer_type whitespace --language russian --percentage_dev 0.95

# 100 samples
python main.py -c experiment_params/xlmr.ini --experiment_name zn_xlmr_100 --path_to_train_set data/MLDoc/mldoc_chinese_train.tsv --path_to_test_set data/MLDoc/mldoc_chinese_test.tsv --tokenizer_type chinese --language chinese --percentage_dev 0.9
python main.py -c experiment_params/xlmr.ini --experiment_name ja_xlmr_100 --path_to_train_set data/MLDoc/mldoc_japanese_train.tsv --path_to_test_set  data/MLDoc/mldoc_japanese_test.tsv --tokenizer_type japanese --language japanese --percentage_dev 0.9
python main.py -c experiment_params/xlmr.ini --experiment_name de_xlmr_100 --path_to_train_set data/MLDoc/mldoc_german_train.tsv --path_to_test_set  data/MLDoc/mldoc_german_test.tsv --tokenizer_type whitespace --language german --percentage_dev 0.9
python main.py -c experiment_params/xlmr.ini --experiment_name es_xlmr_100 --path_to_train_set data/MLDoc/mldoc_spanish_train.tsv --path_to_test_set  data/MLDoc/mldoc_spanish_test.tsv --tokenizer_type whitespace --language spanish --percentage_dev 0.9
python main.py -c experiment_params/xlmr.ini --experiment_name en_xlmr_100 --path_to_train_set data/MLDoc/mldoc_english_train.tsv --path_to_test_set  data/MLDoc/mldoc_english_test.tsv --tokenizer_type whitespace --language english --percentage_dev 0.9
python main.py -c experiment_params/xlmr.ini --experiment_name fr_xlmr_100 --path_to_train_set data/MLDoc/mldoc_french_train.tsv --path_to_test_set  data/MLDoc/mldoc_french_test.tsv --tokenizer_type whitespace --language french --percentage_dev 0.9
python main.py -c experiment_params/xlmr.ini --experiment_name it_xlmr_100 --path_to_train_set data/MLDoc/mldoc_italian_train.tsv --path_to_test_set  data/MLDoc/mldoc_italian_test.tsv --tokenizer_type whitespace --language italian --percentage_dev 0.9
python main.py -c experiment_params/xlmr.ini --experiment_name ru_xlmr_100 --path_to_train_set data/MLDoc/mldoc_russian_train.tsv --path_to_test_set  data/MLDoc/mldoc_russian_test.tsv --tokenizer_type whitespace --language russian --percentage_dev 0.9

# Full data experiments
python main.py -c experiment_params/xlmr.ini --experiment_name zn_xlmr --path_to_train_set data/MLDoc/mldoc_chinese_train.tsv --path_to_test_set data/MLDoc/mldoc_chinese_test.tsv --tokenizer_type chinese --language chinese --percentage_dev 0.1
python main.py -c experiment_params/xlmr.ini --experiment_name ja_xlmr --path_to_train_set data/MLDoc/mldoc_japanese_train.tsv --path_to_test_set  data/MLDoc/mldoc_japanese_test.tsv --tokenizer_type japanese --language japanese --percentage_dev 0.1
python main.py -c experiment_params/xlmr.ini --experiment_name de_xlmr --path_to_train_set data/MLDoc/mldoc_german_train.tsv --path_to_test_set  data/MLDoc/mldoc_german_test.tsv --tokenizer_type whitespace --language german --percentage_dev 0.1
python main.py -c experiment_params/xlmr.ini --experiment_name es_xlmr --path_to_train_set data/MLDoc/mldoc_spanish_train.tsv --path_to_test_set  data/MLDoc/mldoc_spanish_test.tsv --tokenizer_type whitespace --language spanish --percentage_dev 0.1
python main.py -c experiment_params/xlmr.ini --experiment_name fr_xlmr --path_to_train_set data/MLDoc/mldoc_french_train.tsv --path_to_test_set  data/MLDoc/mldoc_french_test.tsv --tokenizer_type whitespace --language french --percentage_dev 0.1
python main.py -c experiment_params/xlmr.ini --experiment_name en_xlmr --path_to_train_set data/MLDoc/mldoc_english_train.tsv --path_to_test_set  data/MLDoc/mldoc_english_test.tsv --tokenizer_type whitespace --language english --percentage_dev 0.1
python main.py -c experiment_params/xlmr.ini --experiment_name it_xlmr --path_to_train_set data/MLDoc/mldoc_italian_train.tsv --path_to_test_set  data/MLDoc/mldoc_italian_test.tsv --tokenizer_type whitespace --language italian --percentage_dev 0.1
python main.py -c experiment_params/xlmr.ini --experiment_name ru_xlmr --path_to_train_set data/MLDoc/mldoc_russian_train.tsv --path_to_test_set  data/MLDoc/mldoc_russian_test.tsv --tokenizer_type whitespace --language russian --percentage_dev 0.1

