python main.py -c experiment_params/bbpe.ini --experiment_name zn_10000-bbpe_20 --num_subwords 10000 --path_to_train_set data/MLDoc/mldoc_chinese_train.tsv path_to_test_set data/MLDoc/mldoc_chinese_test.tsv --tokenizer_type chinese --language chinese --percentage_dev 0.98
python main.py -c experiment_params/bbpe.ini --experiment_name ja_10000-bbpe_20 --num_subwords 10000 --path_to_train_set data/MLDoc/mldoc_japanese_train.tsv --path_to_test_set  data/MLDoc/mldoc_japanese_test.tsv --tokenizer_type japanese --language japanese --percentage_dev 0.98
python main.py -c experiment_params/bbpe.ini --experiment_name de_10000-bbpe_20 --num_subwords 10000 --path_to_train_set data/MLDoc/mldoc_german_train.tsv --path_to_test_set  data/MLDoc/mldoc_german_test.tsv --tokenizer_type whitespace --language german --percentage_dev 0.98
python main.py -c experiment_params/bbpe.ini --experiment_name fr_10000-bbpe_20 --num_subwords 10000 --path_to_train_set data/MLDoc/mldoc_french_train.tsv --path_to_test_set  data/MLDoc/mldoc_french_test.tsv --tokenizer_type whitespace --language french --percentage_dev 0.98
python main.py -c experiment_params/bbpe.ini --experiment_name it10000-bbpe_20 --num_subwords 10000 --path_to_train_set data/MLDoc/mldoc_italian_train.tsv --path_to_test_set  data/MLDoc/mldoc_italian_test.tsv --tokenizer_type whitespace --language italian --percentage_dev 0.98
python main.py -c experiment_params/bbpe.ini --experiment_name ru_10000-bbpe_20 --num_subwords 10000 --path_to_train_set data/MLDoc/mldoc_russian_train.tsv --path_to_test_set  data/MLDoc/mldoc_russian_test.tsv --tokenizer_type whitespace --language russian --percentage_dev 0.98

# 5000
python main.py -c experiment_params/bbpe.ini --experiment_name zn_5000-bbpe_20 --num_subwords 5000 --path_to_train_set data/MLDoc/mldoc_chinese_train.tsv path_to_test_set data/MLDoc/mldoc_chinese_test.tsv --tokenizer_type chinese --language chinese --percentage_dev 0.98
python main.py -c experiment_params/bbpe.ini --experiment_name ja_5000-bbpe_20 --num_subwords 5000 --path_to_train_set data/MLDoc/mldoc_japanese_train.tsv --path_to_test_set  data/MLDoc/mldoc_japanese_test.tsv --tokenizer_type japanese --language japanese --percentage_dev 0.98
python main.py -c experiment_params/bbpe.ini --experiment_name de_5000-bbpe_20 --num_subwords 5000 --path_to_train_set data/MLDoc/mldoc_german_train.tsv --path_to_test_set  data/MLDoc/mldoc_german_test.tsv --tokenizer_type whitespace --language german --percentage_dev 0.98
python main.py -c experiment_params/bbpe.ini --experiment_name fr_5000-bbpe_20 --num_subwords 5000 --path_to_train_set data/MLDoc/mldoc_french_train.tsv --path_to_test_set  data/MLDoc/mldoc_french_test.tsv --tokenizer_type whitespace --language french --percentage_dev 0.98
python main.py -c experiment_params/bbpe.ini --experiment_name it5000-bbpe_20 --num_subwords 5000 --path_to_train_set data/MLDoc/mldoc_italian_train.tsv --path_to_test_set  data/MLDoc/mldoc_italian_test.tsv --tokenizer_type whitespace --language italian --percentage_dev 0.98
python main.py -c experiment_params/bbpe.ini --experiment_name ru_5000-bbpe_20 --num_subwords 5000 --path_to_train_set data/MLDoc/mldoc_russian_train.tsv --path_to_test_set  data/MLDoc/mldoc_russian_test.tsv --tokenizer_type whitespace --language russian --percentage_dev 0.98

#2500
python main.py -c experiment_params/bbpe.ini --experiment_name zn_2500-bbpe_20 --num_subwords 2500 --path_to_train_set data/MLDoc/mldoc_chinese_train.tsv path_to_test_set data/MLDoc/mldoc_chinese_test.tsv --tokenizer_type chinese --language chinese --percentage_dev 0.98
python main.py -c experiment_params/bbpe.ini --experiment_name ja_2500-bbpe_20 --num_subwords 2500 --path_to_train_set data/MLDoc/mldoc_japanese_train.tsv --path_to_test_set  data/MLDoc/mldoc_japanese_test.tsv --tokenizer_type japanese --language japanese --percentage_dev 0.98
python main.py -c experiment_params/bbpe.ini --experiment_name de_2500-bbpe_20 --num_subwords 2500 --path_to_train_set data/MLDoc/mldoc_german_train.tsv --path_to_test_set  data/MLDoc/mldoc_german_test.tsv --tokenizer_type whitespace --language german --percentage_dev 0.98
python main.py -c experiment_params/bbpe.ini --experiment_name fr_2500-bbpe_20 --num_subwords 2500 --path_to_train_set data/MLDoc/mldoc_french_train.tsv --path_to_test_set  data/MLDoc/mldoc_french_test.tsv --tokenizer_type whitespace --language french --percentage_dev 0.98
python main.py -c experiment_params/bbpe.ini --experiment_name it2500-bbpe_20 --num_subwords 2500 --path_to_train_set data/MLDoc/mldoc_italian_train.tsv --path_to_test_set  data/MLDoc/mldoc_italian_test.tsv --tokenizer_type whitespace --language italian --percentage_dev 0.98
python main.py -c experiment_params/bbpe.ini --experiment_name ru_2500-bbpe_20 --num_subwords 2500 --path_to_train_set data/MLDoc/mldoc_russian_train.tsv --path_to_test_set  data/MLDoc/mldoc_russian_test.tsv --tokenizer_type whitespace --language russian --percentage_dev 0.98

#1000
python main.py -c experiment_params/bbpe.ini --experiment_name zn_1000-bbpe_20 --num_subwords 1000 --path_to_train_set data/MLDoc/mldoc_chinese_train.tsv path_to_test_set data/MLDoc/mldoc_chinese_test.tsv --tokenizer_type chinese --language chinese --percentage_dev 0.98
python main.py -c experiment_params/bbpe.ini --experiment_name ja_1000-bbpe_20 --num_subwords 1000 --path_to_train_set data/MLDoc/mldoc_japanese_train.tsv --path_to_test_set  data/MLDoc/mldoc_japanese_test.tsv --tokenizer_type japanese --language japanese --percentage_dev 0.98
python main.py -c experiment_params/bbpe.ini --experiment_name de_1000-bbpe_20 --num_subwords 1000 --path_to_train_set data/MLDoc/mldoc_german_train.tsv --path_to_test_set  data/MLDoc/mldoc_german_test.tsv --tokenizer_type whitespace --language german --percentage_dev 0.98
python main.py -c experiment_params/bbpe.ini --experiment_name fr_1000-bbpe_20 --num_subwords 1000 --path_to_train_set data/MLDoc/mldoc_french_train.tsv --path_to_test_set  data/MLDoc/mldoc_french_test.tsv --tokenizer_type whitespace --language french --percentage_dev 0.98
python main.py -c experiment_params/bbpe.ini --experiment_name it1000-bbpe_20 --num_subwords 1000 --path_to_train_set data/MLDoc/mldoc_italian_train.tsv --path_to_test_set  data/MLDoc/mldoc_italian_test.tsv --tokenizer_type whitespace --language italian --percentage_dev 0.98
python main.py -c experiment_params/bbpe.ini --experiment_name ru_1000-bbpe_20 --num_subwords 1000 --path_to_train_set data/MLDoc/mldoc_russian_train.tsv --path_to_test_set  data/MLDoc/mldoc_russian_test.tsv --tokenizer_type whitespace --language russian --percentage_dev 0.98
